// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	Phone        string    `gorm:"column:phone;not null" json:"phone"`
	Password     string    `gorm:"column:password;not null" json:"password"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Avatar       string    `gorm:"column:avatar;not null" json:"avatar"`
	Sex          int32     `gorm:"column:sex;default:3;comment: 123" json:"sex"`                     //  123
	ActiveStatus int32     `gorm:"column:active_status;default:2;comment: 1 2" json:"active_status"` //  1 2
	LastOptTime  time.Time `gorm:"column:last_opt_time;not null;default:CURRENT_TIMESTAMP(3)" json:"last_opt_time"`
	IPInfo       string    `gorm:"column:ip_info;comment:ip" json:"ip_info"`            // ip
	ItemID       int64     `gorm:"column:item_id;comment:id" json:"item_id"`            // id
	Status       int32     `gorm:"column:status;default:1;comment: 1. 2" json:"status"` //  1. 2
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3)" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3)" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
