// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户id" json:"id"`                                  // 用户id
	Phone        string    `gorm:"column:phone;not null;comment:用户手机" json:"phone"`                                                 // 用户手机
	Password     string    `gorm:"column:password;not null;comment:用户密码" json:"password"`                                           // 用户密码
	Name         string    `gorm:"column:name;not null;comment:用户昵称" json:"name"`                                                   // 用户昵称
	Avatar       string    `gorm:"column:avatar;not null;comment:用户头像" json:"avatar"`                                               // 用户头像
	Sex          int32     `gorm:"column:sex;default:3;comment:性别 1为男性，2为女性，3未知" json:"sex"`                                        // 性别 1为男性，2为女性，3未知
	ActiveStatus int32     `gorm:"column:active_status;default:2;comment:在线状态 1在线 2离线" json:"active_status"`                        // 在线状态 1在线 2离线
	LastOptTime  time.Time `gorm:"column:last_opt_time;not null;default:CURRENT_TIMESTAMP(3);comment:最后上下线时间" json:"last_opt_time"` // 最后上下线时间
	IPInfo       string    `gorm:"column:ip_info;comment:ip信息，用于显示用户地理位置" json:"ip_info"`                                           // ip信息，用于显示用户地理位置
	ItemID       int64     `gorm:"column:item_id;comment:佩戴的徽章id" json:"item_id"`                                                   // 佩戴的徽章id
	Status       int32     `gorm:"column:status;default:1;comment:使用状态 1.正常 2禁用" json:"status"`                                     // 使用状态 1.正常 2禁用
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_time"`        // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3);comment:修改时间" json:"update_time"`        // 修改时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
